# Generated by Django 2.2.5 on 2020-11-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttentionMiddlePeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='账号')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='密码')),
                ('choice_classfiy', models.SmallIntegerField(choices=[(0, '最高权限'), (1, '一级用户'), (2, '二级用户'), (3, '三级用户'), (4, '四级用户')], default=0, verbose_name='类型')),
            ],
            options={
                'verbose_name': '管理账户',
                'verbose_name_plural': '管理账户',
                'db_table': 'tb_account_executive',
                'managed': True,
            },
        ),
    ]
