# Generated by Django 2.2.5 on 2020-11-28 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttentionMiddlePeople',
            new_name='AccountExecutive',
        ),
    ]
