from django.urls import re_path
from . import views

urlpatterns = [
    # 登陆时需要获取某参数
    re_path(r'^come$', views.LoginInTimeGiveValue.as_view()),
    # session
    re_path('session', views.test_session),
    # code
    re_path(r'^authorize/$', views.authorize, name='authorize'),
    # 获取头像等信息存储
    re_path(r'^put/$', views.SafeUserWechatValueView.as_view()),
    # h5登陆
    re_path(r'^login$', views.LoginView.as_view()),
    # wechat绑定
    re_path(r'^bind$', views.WechatBindingView.as_view()),
    # 关注的楼盘
    re_path(r'^at_vil$', views.UsersAttionBuildingView.as_view()),
    # 普通用户关注的文章
    re_path(r'^at_art$', views.UsersAttionArticalgView.as_view()),
    # 用户关注的置业顾问
    re_path(r'^at_mp$', views.UsersAttionMiddlePeopleView.as_view()),
    # 我的摇号查询列表
    re_path(r'^au_lo$', views.MyLotteryView.as_view()),
    # 我的编码查询列表
    re_path(r'^au_co$', views.MyCodeView.as_view()),
    # 问题反馈
    re_path(r'^au_fk$', views.QuestionUploadView.as_view()),
    # 置业顾问入驻
    re_path(r'^mp_rz$', views.MiddlePeopleGetView.as_view()),
    # 顾问之家列表页
    re_path(r'^gw_list$', views.MiddlePeopleHouseDetialView.as_view()),
    # 顾问之家电话
    re_path(r'^gw_phone$', views.MiddlePhoneView.as_view()),
    # 顾问之家聊天
    re_path(r'^gw_chat$', views.MyWeChatView.as_view()),
    # 顾问之家专属客户
    re_path(r'^gw_custmer$', views.MiddleCustmerView.as_view()),
    # 顾问之家积分明细表
    re_path(r'^gw_sub$', views.MiddleFenView.as_view()),
    # 顾问之家金币明细
    re_path(r'^gw_money$', views.MiddleMoneyView.as_view()),
    # 专属海报
    re_path(r'^gw_hb$', views.SeaPaperView.as_view()),
    # 置业顾问我的楼盘
    re_path(r'^gw_vil$', views.MiddleVillageView.as_view()),
    # 生成户型海报
    re_path(r'^gw_hxhb$', views.CreateHouseXingImgView.as_view()),
    # 生成个人名片
    re_path(r'^gw_grmp$', views.CreateMingPianImgView.as_view()),
    # 一房一价海报
    re_path(r'^gw_yfyjhb$', views.MiddlePeopleOneHouseOnePriceCreateView.as_view()),
    # 置业顾问详情页
    re_path(r'^gw_detial$', views.MiddlePeopleDetialView.as_view()),
    # 谁看过我
    re_path(r'^gw_help_z$', views.WhoLookMeView.as_view()),
    # 置业顾问分享
    re_path(r'^gw_share$', views.HeFenXiangView.as_view()),
    # 他的回答
    re_path(r'^gw_answer$', views.HeAnswerView.as_view()),
    # 点击关注顾问
    re_path(r'^gw_at_guan$', views.ClickMiddlePeopleAttentionView.as_view()),
    # 全站/楼盘竞价页
    re_path(r'^gw_pk_mo$', views.MyWillGoView.as_view()),
    # 顾问竞价详情页
    re_path(r'^gw_pk_de$', views.PKMoneyView.as_view()),
    # 金币兑换页详情页
    re_path(r'^gw_con$', views.RequestGlodenMoneyConversionView.as_view()),
    # 实名分享
    re_path(r'^sm_fx$', views.GodView.as_view()),
    # 每日任务首页
    re_path(r'^gw_mrrw$', views.EveryDayPermitionView.as_view()),
    # 选择楼盘(表单)
    re_path(r'^cbnv$', views.ChoiceBuildingNameView.as_view()),
    # 个人中心三个数
    re_path(r'^user_three$', views.UserCenterSystemView.as_view()),
    # 免费打电话
    re_path(r'^call$', views.UserCallFreeToMiddlePeopleView.as_view()),
    # 每日任务之关注公众号
    re_path(r'^gzgzh$', views.PayAttentionToAuthorizedPublicAccountView.as_view()),
    # 每日任务之分享小程序给新用户
    re_path(r'^xyhfxxcx$', views.ShareSmallProgramsWithNewUsersView.as_view()),
    # 每日任务之分享小程序给老用户
    re_path(r'^lyhfxxcx$', views.ShareSmallProgramsWithOldUsersView.as_view()),
    # 每日任务之转发朋友圈
    re_path(r'^zfpyq$', views.RetweetingMomentsView.as_view()),
    # 每日任务之发布分享唐
    re_path(r'^fbfxt$', views.IssueShareView.as_view()),
    # 每日任务之积分问题反馈
    re_path(r'^wtfkjf$', views.ProvideImportantInformationView.as_view()),
    # 每日任务之邀请置业顾问入驻
    re_path(r'^yqzygwrz$', views.PleaseMiddlePeopleView.as_view()),
    # 每日任务之上传楼盘信息
    re_path(r'^sclpxxjf$', views.UploadBuildingDetialView.as_view()),
    # 我的楼盘之楼盘状态
    re_path(r'^wdlpzlpzt$', views.MyBuildingStatueView.as_view()),
    # 举报
    re_path(r'^user_jb$', views.UserReportView.as_view()),
    # 展业工具
    re_path(r'^mp_show$', views.ShowPageView.as_view()),
    # 楼盘详情页我的摇号接口显示
    re_path(r'^dt_mlshow$', views.BuildingDetialMyLotteryView.as_view()),
    # 摇号提醒
    re_path(r'^bd_lr$', views.LotteryRemindView.as_view()),
    # 删除添加的编码
    re_path(r'^sctjbm', views.DeleteMyLotteryNumberView.as_view()),
    # 判断用户是否关注
    re_path(r'^if_bdmp$', views.IfZanView.as_view()),
    # 封号状态查询
    re_path(r'^user/login/check$', views.UserSealStatusView.as_view()),
    # execl上传
    re_path(r'^admin/execlwpload$', views.ExeclUploadView.as_view()),
    # 即时通讯列表页/删除/添加
    re_path(r'^user/ws/chat/listccc$', views.UserChatListCreateDelView.as_view()),
    # 即时通讯消息列表页
    re_path(r'^user/ws/chat/list$', views.UserChatListView.as_view()),
    # 消息详情页
    re_path(r'^user/ws/chat/xxxqy$', views.UserChatHistoryView.as_view()),
    # 个人中心任务状态栏显示/加积分-活跃度
    re_path(r'^user/grzxztlxsjjfhyd$', views.EveryDayPermetionView.as_view()),
    # 判断用户是否绑定
    re_path(r'^user/pdyhsfbd$', views.PanMobileView.as_view()),
]