# Generated by Django 2.2.5 on 2020-12-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplateValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=255, verbose_name='模板id编号')),
                ('template_name', models.CharField(max_length=255, verbose_name='模板名称')),
                ('template_recode', models.CharField(max_length=255, verbose_name='回复内容')),
                ('choice_classfiy', models.SmallIntegerField(choices=[(0, '停止使用'), (1, '正在使用')], default=0, verbose_name='是否使用')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '消息模板',
                'verbose_name_plural': '消息模板',
                'db_table': 'tb_message_template_value',
                'managed': True,
            },
        ),
    ]
