# Generated by Django 2.2.5 on 2020-12-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_message', '0002_messagetemplatevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplatevalue',
            name='template_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='模板id编号'),
        ),
        migrations.AlterField(
            model_name='messagetemplatevalue',
            name='template_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='模板名称'),
        ),
        migrations.AlterField(
            model_name='messagetemplatevalue',
            name='template_recode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='回复内容'),
        ),
    ]
