# Generated by Django 2.2.5 on 2021-01-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_message', '0003_auto_20201217_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplatevalue',
            name='class_types',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='接收提醒的用户'),
        ),
        migrations.AddField(
            model_name='messagetemplatevalue',
            name='send_message_time',
            field=models.TimeField(blank=True, null=True, verbose_name='定时发送'),
        ),
        migrations.AddField(
            model_name='messagetemplatevalue',
            name='status',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='状态'),
        ),
    ]
