from django.urls import re_path
from . import views

urlpatterns = [
    # 楼盘详情页
    re_path(r'^detial$', views.BuildingDetialView.as_view()),
    # 搜索框/找房
    re_path(r'^search/$', views.SearchView.as_view()),
    # 广告
    re_path(r'^ad/$', views.WheelImageView.as_view()),
    # 热门楼盘
    re_path(r'^notice/$', views.HotDoorBuildingView.as_view()),
    # 即将预售
    re_path(r'^five/$', views.WillSaleView.as_view()),
    # 线上售楼部
    re_path(r'^online/$', views.OnlineSaleBuildingView.as_view()),
    # 楼盘动态
    re_path(r'^dynamic/$', views.VillageDynamicView.as_view()),
    # Vs
    re_path(r'^vs/$', views.VsView.as_view()),
    # Vs详情页
    re_path(r'^vs_d/', views.VsDetialView.as_view()),
    # 楼盘详细信息
    re_path(r'^hdetial/', views.BuildingHouseDetialView.as_view()),
    # 公示方案
    re_path(r'^gongs/$', views.PublicityView.as_view()),
    # 小滑块
    re_path(r'^hua/$', views.SmallVillageSellStateView.as_view()),
    # 意向登记
    re_path(r'^yxdjb/$', views.IntentRegisterView.as_view()),
    # 摇号结果
    re_path(r'^yhjg/$', views.BuildingLotteryResultView.as_view()),
    # 搜索摇号
    re_path(r'^ssyh/$', views.SearchLotteryNumberView.as_view()),
    # 一房一价列表页
    re_path(r'^yfyjl/$', views.OneHouseOnePriceListView.as_view()),
    # 一房一价取号页
    re_path(r'^yfyjqhy$', views.OneHouseOnePriceTitleListView.as_view()),
    # 一房一价详情页
    re_path(r'^yfyj/$', views.OneHouseOnePriceDetailView.as_view()),
    # 摇号常见问题
    re_path(r'^seven/$', views.HousePurchaseInformationPageView.as_view()),
    # 一键找房
    re_path(r'^find/$', views.OneKeyFindHouseView.as_view()),
    # 周边楼盘
    re_path(r'^zb/$', views.RimVillageView.as_view()),
    # 同价位楼盘
    re_path(r'^tjlp/$', views.SamePriceVillageView.as_view()),
    # 地图找房
    re_path(r'^map/$', views.MapHouseView.as_view()),
    # 地铁找房
    re_path(r'^train/$', views.TranFindHouseView.as_view()),
    # # 周边配套
    # re_path(r'^zbpt/$', views.SurroundingFacilityView.as_view()),
    # 购房百科搜索框
    re_path(r'^bkss/$', views.SearchBuyHouseHundredDepartmentView.as_view()),
    # 购房百科列表页(热门问题)
    re_path(r'^bklby/$', views.BuyHouseHundredDepartmentView.as_view()),
    # 购房百科
    re_path(r'^baike/$', views.KnowlageKnowView.as_view()),
    # 购房百科详情页
    re_path(r'^bkdetial/$', views.BuyHouseHundredDepartmentDetialView.as_view()),
    # 公众号/购房群/服务号
    re_path(r'^ggfimg/$', views.ThreeImageView.as_view()),
    # 历史摇号
    re_path(r'^lsyh/$', views.HistoryAndLotteryView.as_view()),
    # 历史摇号详情页
    re_path(r'^lsyhxxy/$', views.HistoryAndLotteryDetialView.as_view()),
    # 文章搜索框
    re_path(r'^wzsearch/$', views.SearchArticalView.as_view()),
    # 最新文章
    re_path(r'^newartical/$', views.NewArticletView.as_view()),
    # 四组件 买房干货/楼市解读/楼市百科/房产投资
    re_path(r'^four/$', views.ArticleFourView.as_view()),
    # 土拍搜索框
    re_path(r'^tpsearch/$', views.GetSoilShotSearchView.as_view()),
    # 土拍列表页/列表首页/区域分类/住宅类型分类
    re_path(r'^tplist/$', views.GetSoilShotListView.as_view()),
    # 土拍详情页
    re_path(r'^tpdetial/$', views.GetSoilShotView.as_view()),
    # 首页优秀顾问3个
    re_path(r'^three/$', views.MiddlePersonTopThreeView.as_view()),
    # 分享唐搜索
    re_path(r'^fxtsearch/$', views.SharingSearchView.as_view()),
    # 分享堂列表页全部搜索
    re_path(r'^fxtlist/$', views.SharingSearchListView.as_view()),
    # # 分享堂列表页我的关注
    # re_path(r'^fxtlistw/$', views.MySharingAttentionView.as_view()),
    # 问答列表页/列表首页
    re_path(r'^wdlistindex/$', views.QuestionAnswerView.as_view()),
    # 问答浏览量及创建时间排序
    re_path(r'^timeorder/$', views.QuestionAnswerTypeOrderView.as_view()),
    # 问答详情页
    re_path(r'^qadetial/$', views.QuestionAnswerDetialView.as_view()),
    # 生成问题海报
    re_path(r'^wthb/$', views.CreateSeaPaperView.as_view()),
    # 头条
    re_path(r'^tt/$', views.HeadersNuddleView.as_view()),
    # 我要提问
    re_path(r'^wytw/$', views.IWantToQuestionView.as_view()),
    # 系统消息
    re_path(r'^xtxx/$', views.SystemMessageView.as_view()),
    # 置业顾问排行列表页
    re_path(r'^zygwph/$', views.AdviserView.as_view()),
    # 楼盘详情页专业顾问推荐
    re_path(r'^lpgwtj/$', views.MiddleTuiView.as_view()),
    # 联系更多顾问
    re_path(r'^gdgw/$', views.NotSellPeopleView.as_view()),
    # 首页我关注的楼盘
    re_path(r'^sywgzdlp/$', views.AttentionView.as_view()),
    # 楼盘评论列表页
    re_path(r'^lppllby/$', views.HouseCommentView.as_view()),
    # 楼盘评论更多
    re_path(r'^lpplgd/$', views.MoreAdviserView.as_view()),
    # 置业顾问回答问题
    re_path(r'^zygwhdwt$', views.IWantToAnswerView.as_view()),
    # 成交排行/区域最新
    re_path(r'^tp_c_q$', views.DetialShotListViewGetSoilOrderByView.as_view()),
    # 户型图
    re_path(r'^hxt$', views.HouseImageView.as_view()),
    # 相册
    re_path(r'^xc$', views.HouseImgView.as_view()),
    # 视频
    re_path(r'^sp$', views.HouseVideoView.as_view()),
    # 问答搜索框
    re_path(r'^wd_search$', views.QuestionAnswerSearchView.as_view()),
    # 给评论点赞
    re_path(r'^g_zz$', views.GiveCommentAdviserView.as_view()),
    # 删除回答
    re_path(r'^d_an$', views.DeleteAnswerAndZanView.as_view()),
    # 给回答取消赞
    re_path(r'^g_a_d$', views.GiveAnswerDisZanView.as_view()),
    # 文章详情页
    re_path(r'^aredetial$', views.ArticletVieView.as_view()),
    # 贷款计算
    re_path(r'^dkjs$', views.CalculateView.as_view()),
    # 提前还款计算
    re_path(r'^tqhkjs$', views.PrepaymentCalculationView.as_view()),
    # 总平图
    re_path(r'^zpt$', views.AllCapteo.as_view()),
    # 统计五个组件
    re_path(r'^tjwzj$', views.IndexCountView.as_view()),
    # 楼盘评论之点评    
    re_path(r'^lpplzdp$', views.ClickCommentView.as_view()),
    # 第一个评论
    re_path(r'^firstc$', views.FirstCommentView.as_view()),
    # 经纬度入库
    re_path(r'^jwd/$', views.LongLatCreateView.as_view()),
    # 筛选查询
    re_path(r'^fqfind/$', views.FilterQueryView.as_view()),
    
    # 公众号/服务号/买房群/上传
    re_path(r'^santup/ccc$', views.ThreeImageCreateView.as_view()),
    # 公众号/服务号/买房群/删除
    re_path(r'^santup/ddd$', views.ThreeImageDelView.as_view()),
    # 用户访问楼盘记录
    re_path(r'^yhfwlpjl/$', views.UserLookBuildingView.as_view()),
    # 周边配套经纬度入库
    re_path(r'^zbptjwdrk$', views.SurroundingFacilityLocationView.as_view()),
    # 此乃首页
    re_path(r'^$', views.HomePageView.as_view()),
    #start index增加
    #获取杭州所有区域
    re_path(r'^landAllList$', views.LandDistrictListView.as_view()),
    #获取杭州所有地铁线
    re_path(r'^subwayAllList$', views.SubwayListView.as_view())
    #end  index增加
]