from django.urls import re_path
from . import views

urlpatterns = [
    # 用户登录
    re_path(r'^admin/login$', views.AdminBackendLogin.as_view()),
    # 楼盘详情/搜索 - 图片搜索
    re_path(r'^adm/bds$', views.BuildingDetialSearchView.as_view()),
    # 楼盘列表页
    re_path(r'^adm/list$', views.BuildingListPageView.as_view()),
    # 楼盘详情/查-改
    re_path(r'^adm/bd$', views.BuildingDetialView.as_view()),
    # 楼盘详情/添加
    re_path(r'^adm/bdadd$', views.BuildingDetialADDView.as_view()), # 改单
    # 楼盘详情/删除
    re_path(r'^adm/bdd$', views.BuildingDetialDelView.as_view()),
    # 楼盘图片查询(按分类)/改
    re_path(r'^adm/bdi$', views.BuildingImageView.as_view()),
    # 楼盘图片/上传
    re_path(r'^adm/bdiu$', views.BuildingImageCreateView.as_view()),
    # 楼盘图片/删除
    re_path(r'^adm/bdid$', views.BuildingImageDelView.as_view()),
    # 楼盘视频查询(按分类)/改
    re_path(r'^adm/bdv$', views.BuildingVideoView.as_view()),
    # 楼盘视频/上传
    re_path(r'^adm/bdvu$', views.BuildingVideoCreateView.as_view()),
    # 楼盘视频/删除
    re_path(r'^adm/bdvd$', views.BuildingVideoDelView.as_view()),
    # 楼盘动态信息/查/改
    re_path(r'^adm/bdm$', views.BuildingStatueMessageView.as_view()),
    # 楼盘动态信息/发表
    re_path(r'^adm/bdmu$', views.BuildingStatueMessageCreateView.as_view()),
    # 楼盘动态信息/删除
    re_path(r'^adm/bdmd$', views.BuildingStatueMessageDelView.as_view()),
    # 楼盘户型图/查/改
    re_path(r'^adm/bdh$', views.BuildingHouseImageView.as_view()),
    # 楼盘户型图/上传
    re_path(r'^adm/bdhu$', views.BuildingHouseImageCreateView.as_view()),
    # 楼盘户型图/删除
    re_path(r'^adm/bdhd$', views.BuildingHouseImageDelView.as_view()),
    # 一房一价/查/改
    re_path(r'^adm/yfyj$', views.OneHouseOnePriceView.as_view()),
    # 一房一价/上传 # 一房一价总数据
    re_path(r'^adm/yfyju$', views.OneHouseOnePriceCreateView.as_view()),
    # 一房一价/删除
    re_path(r'^adm/yfyjd$', views.OneHouseOnePriceDelView.as_view()),
    # vr/航拍/总评 - 查/改
    re_path(r'^adm/vfl$', views.VRFlyAllImageView.as_view()),
    # vr/航拍/总评/ - 上传 # 总总平/查
    re_path(r'^adm/vflu$', views.VRFlyAllImageCreateView.as_view()),
    # vr/航拍/总评/ - 删除
    re_path(r'^adm/vfld$', views.VRFlyAllImageDelView.as_view()),
    # 历史摇号信息/查/改
    re_path(r'^adm/hl$', views.HistoryLotteryMessageView.as_view()),
    # 历史摇号信息/上传 # 总摇号数据
    re_path(r'^adm/hlu$', views.HistoryLotteryMessageCreateView.as_view()),
    # 历史摇号信息/删除
    re_path(r'^adm/hld$', views.HistoryLotteryMessageDelView.as_view()),
    # 意向登记/查/改
    re_path(r'^adm/yxdj$', views.IntentToRegisterView.as_view()),
    # 意向登记/上传 # 总意向登记/查
    re_path(r'^adm/yxdju$', views.IntentToRegisterCreateView.as_view()),
    # 意向登记/删除
    re_path(r'^adm/yxdjd$', views.IntentToRegisterDelView.as_view()),
    # 入驻的置业顾问/查/改
    re_path(r'^adm/rzzygw$', views.EnterBuildingMiddlePeopleView.as_view()),
    # 入驻的置业顾问/上传
    re_path(r'^adm/rzzygwu$', views.EnterBuildingMiddlePeopleCreateView.as_view()),
    # 入驻的置业顾问/删除
    re_path(r'^adm/rzzygwd$', views.EnterBuildingMiddlePeopleDelView.as_view()),
    # 关注该楼盘的用户/查/改
    re_path(r'^adm/yh$', views.AttentionBuildingUsersView.as_view()),
    # 关注该楼盘的用户/上传
    re_path(r'^adm/yhc$', views.AttentionBuildingUsersCreateView.as_view()),
    # 关注该楼盘的用户/删除
    re_path(r'^adm/yhd$', views.AttentionBuildingUsersDelView.as_view()),
    # 楼盘评论/查/改
    re_path(r'^adm/pl$', views.BuildingCommentView.as_view()),
    # 楼盘评论/上传 # 总楼盘评论数据
    re_path(r'^adm/plc$', views.BuildingCommentCreateView.as_view()),
    # 楼盘评论/删除
    re_path(r'^adm/pld$', views.BuildingCommentDelView.as_view()),
    # 楼盘销售时间/查/改
    re_path(r'^adm/bdst$', views.BuildingSaleTimeView.as_view()),
    # 楼盘销售时间/上传 # 总楼盘销售时间/查
    re_path(r'^adm/bdstc$', views.BuildingSaleTimeCreateView.as_view()),
    # 楼盘销售时间/删除
    re_path(r'^adm/bdstd$', views.BuildingSaleTimeDelView.as_view()),
    # 楼盘详情页竞价/查/改
    re_path(r'^adm/bddjj$', views.BuildingDetialPKView.as_view()),
    # 楼盘详情页竞价/上传 # 总楼盘详情页竞价/查
    re_path(r'^adm/bddjjc$', views.BuildingDetialPKCreateView.as_view()),
    # 楼盘详情页竞价/删除
    re_path(r'^adm/bddjjd$', views.BuildingDetialPKDelView.as_view()),
    # 预售证
    re_path(r'^adm/wscn$', views.WillSaleCardView.as_view()),
    # 顾问搜索框
    re_path(r'^mp/s$', views.MiddlePeopleSearchView.as_view()),
    # 顾问列表页
    re_path(r'^mp/l$', views.MiddlePeopleListView.as_view()),
    # 顾问基本信息/查/改
    re_path(r'^mp/bi$', views.MiddlePeopleBasicInformationView.as_view()),
    # 顾问基本信息/上传
    re_path(r'^mp/bic$', views.MiddlePeopleBasicInformationCreateView.as_view()),
    # 顾问基本信息/删除
    re_path(r'^mp/bid$', views.MiddlePeopleBasicInformationDelView.as_view()),
    # 顾问点赞记录/查/改
    re_path(r'^mp/cz$', views.MiddlePeopleClickZanRecordView.as_view()),
    # 顾问点赞记录/上传
    re_path(r'^mp/czc$', views.MiddlePeopleClickZanRecordCreateView.as_view()),
    # 顾问点赞记录/删除
    re_path(r'^mp/czd$', views.MiddlePeopleClickZanRecordDelView.as_view()),
    # 顾问聊天记录/查/改
    re_path(r'^mp/c$', views.MiddlePeopleChatRecordView.as_view()),
    # 顾问聊天记录/上传 # 总聊天顾问记录
    re_path(r'^mp/cc$', views.MiddlePeopleChatRecordCreateView.as_view()),
    # 顾问聊天记录/删除
    re_path(r'^mp/cd$', views.MiddlePeopleChatRecordDelView.as_view()),
    # 顾问访客记录/查/改
    re_path(r'^mp/cr$', views.MiddlePeopleCustmerRecordView.as_view()),
    # 顾问访客记录/上传
    re_path(r'^mp/crc$', views.MiddlePeopleCustmerRecordCreateView.as_view()),
    # 顾问访客记录/删除
    re_path(r'^mp/crd$', views.MiddlePeopleCustmerRecordDelView.as_view()),
    # 顾问来电记录/查/改
    re_path(r'^mp/cr$', views.MiddlePeopleComeMobileRecordView.as_view()),
    # 顾问来电记录/上传
    re_path(r'^mp/crc$', views.MiddlePeopleComeMobileRecordCreateView.as_view()),
    # 顾问来电记录/删除
    re_path(r'^mp/crd$', views.MiddlePeopleComeMobileRecordDelView.as_view()),
    # 顾问专属客户记录/查/改
    re_path(r'^mp/ec$', views.MiddlePeopleExclusiveCustmerRecordView.as_view()),
    # 顾问专属客户记录/上传
    re_path(r'^mp/ecc$', views.MiddlePeopleExclusiveCustmerRecordCreateView.as_view()),
    # 顾问专属客户记录/删除
    re_path(r'^mp/ecd$', views.MiddlePeopleExclusiveCustmerRecordDelView.as_view()),
    # 顾问获客神器记录/查/改
    re_path(r'^mp/gcgm$', views.MiddlePeopleGetCustmerGodMachineRecordView.as_view()),
    # 顾问获客神器记录/上传
    re_path(r'^mp/gcgmc$', views.MiddlePeopleGetCustmerGodMachineRecordCreateView.as_view()),
    # 顾问获客神器记录/删除
    re_path(r'^mp/gcgmd$', views.MiddlePeopleGetCustmerGodMachineRecordDelView.as_view()),
    # 顾问金币表记录/查/改
    re_path(r'^mp/g$', views.MiddlePeopleGoldenRecordView.as_view()),
    # 顾问金币表记录/上传
    re_path(r'^mp/gc$', views.MiddlePeopleGoldenRecordCreateView.as_view()),
    # 顾问金币表记录/删除
    re_path(r'^mp/gd$', views.MiddlePeopleGoldenRecordDelView.as_view()),
    # 顾问积分记录/查/改
    re_path(r'^mp/sco$', views.MiddlePeopleScoreRecordView.as_view()),
    # 顾问积分记录/上传
    re_path(r'^mp/scoc$', views.MiddlePeopleScoreRecordCreateView.as_view()),
    # 顾问积分记录/删除
    re_path(r'^mp/scod$', views.MiddlePeopleScoreRecordDelView.as_view()),
    # 顾问入住楼盘记录/查/改
    re_path(r'^mp/gth$', views.MiddlePeopleGoToHouseRecordView.as_view()),
    # 顾问入住楼盘记录/上传
    re_path(r'^mp/gthc$', views.MiddlePeopleGoToHouseCreateView.as_view()),
    # 顾问入住楼盘记录/删除
    re_path(r'^mp/gthd$', views.MiddlePeopleGoToHouseDelView.as_view()),
    # 用户搜索框
    re_path(r'^ur/search$', views.UsersSearchView.as_view()),
    # 用户基本信息/查/改
    re_path(r'^ur/ubi$', views.UsersBasicInformationRecordView.as_view()),
    # 用户基本信息/上传
    re_path(r'^ur/ubic$', views.UsersBasicInformationCreateView.as_view()),
    # 用户基本信息/删除
    re_path(r'^ur/ubid$', views.UsersBasicInformationDelView.as_view()),
    # 用户登陆记录/查/改
    re_path(r'^ur/ulr$', views.UsersLoginRecordView.as_view()),
    # 用户登陆记录/上传
    re_path(r'^ur/ulrc$', views.UsersLoginCreateView.as_view()),
    # 用户登陆记录/删除
    re_path(r'^ur/ulrd$', views.UsersLoginDelView.as_view()),
    # 用户访问楼盘记录/查/改
    re_path(r'^ur/ulbr$', views.UsersLookBuildingRecordView.as_view()),
    # 用户访问楼盘记录/上传
    re_path(r'^ur/ulbrc$', views.UsersLookBuildingCreateView.as_view()),
    # 用户访问楼盘记录/删除
    re_path(r'^ur/ulbrd$', views.UsersLookBuildingDelView.as_view()),
    # 用户聊天记录/查/改
    re_path(r'^ur/ucrc$', views.UsersChatRecordView.as_view()),
    # 用户聊天记录/上传 # 总用户聊天记录
    re_path(r'^ur/ucrcc$', views.UsersChatCreateView.as_view()),
    # 用户聊天记录/删除
    re_path(r'^ur/ucrdd$', views.UsersChatDelView.as_view()),
    # 用户摇号数据记录/查/改
    re_path(r'^ur/ulrr$', views.UsersLotteryRecordView.as_view()),
    # 用户摇号数据记录/上传
    re_path(r'^ur/ulrrc$', views.UsersLotteryCreateView.as_view()),
    # 用户摇号数据记录/删除
    re_path(r'^ur/ulrrd$', views.UsersLotteryDelView.as_view()),
    # 用户关注的文章记录/查/改
    re_path(r'^ur/aalr$', views.UsersAttentionArticalRecordView.as_view()),
    # 用户关注的文章记录/上传
    re_path(r'^ur/aalrc$', views.UsersAttentionArticalCreateView.as_view()),
    # 用户关注的文章记录/删除
    re_path(r'^ur/aalrd$', views.UsersAttentionArticalDelView.as_view()),
    # 用户关注的楼盘记录/查/改
    re_path(r'^ur/abr$', views.UsersAttentionBuildingRecordView.as_view()),
    # 用户关注的楼盘记录/上传
    re_path(r'^ur/abrc$', views.UsersAttentionBuildingCreateView.as_view()),
    # 用户关注的楼盘记录/删除
    re_path(r'^ur/abrd$', views.UsersAttentionBuildingDelView.as_view()),
    # 用户关注的置业顾问记录/查/改
    re_path(r'^ur/amr$', views.UsersAttentionMiddlePeopleRecordView.as_view()),
    # 用户关注的置业顾问记录/上传
    re_path(r'^ur/amrc$', views.UsersAttentionMiddlePeopleCreateView.as_view()),
    # 用户关注的置业顾问记录/删除
    re_path(r'^ur/amrd$', views.UsersAttentionMiddlePeopleDelView.as_view()),
    # 用户编码记录/查/改
    re_path(r'^ur/uccr$', views.UsersCodeRecordView.as_view()),
    # 用户编码记录/上传
    re_path(r'^ur/uccrc$', views.UsersCodeCreateView.as_view()),
    # 用户编码记录/删除
    re_path(r'^ur/uccrd$', views.UsersCodeDelView.as_view()),
    # 购房百科/查/改
    re_path(r'^gf/c$', views.BuyHouseHundredView.as_view()),
    # 购房百科/上传
    re_path(r'^gf/cr$', views.BuyHouseHundredCreateView.as_view()),
    # 购房百科/删除
    re_path(r'^gf/d$', views.BuyHouseHundredDelView.as_view()),
    # 问答/查/改
    re_path(r'^wdw/c$', views.QuestionAnswerView.as_view()),
    # 问答/上传
    re_path(r'^wdw/cr$', views.QuestionAnswerCreateView.as_view()),
    # 问答/删除
    re_path(r'^wdw/d$', views.QuestionAnswerDelView.as_view()),
    # 土拍/查/改
    re_path(r'^tp/c$', views.LandDealView.as_view()),
    # 土拍/上传
    re_path(r'^tp/cr$', views.LandDealCreateView.as_view()),
    # 土拍/删除
    re_path(r'^tp/d$', views.LandDealDelView.as_view()),
    # 分享堂/查/改
    re_path(r'^fxt/c$', views.ShareView.as_view()),
    # 分享堂/上传
    re_path(r'^fxt/cr$', views.ShareCreateView.as_view()),
    # 分享堂/删除
    re_path(r'^fxt/d$', views.ShareDelView.as_view()),
    # 系统消息/查/改
    re_path(r'^xtxx/c$', views.SystemMessageSetView.as_view()),
    # 系统消息/上传
    re_path(r'^xtxx/cr$', views.SystemMessageSetCreateView.as_view()),
    # 系统消息/删除
    re_path(r'^xtxx/d$', views.SystemMessageSetDelView.as_view()),
    # 首页广告竞价/查/改
    re_path(r'^ipk/c$', views.IndexAdvertisingPKSetView.as_view()),
    # 首页广告竞价/上传 # 上楼盘之设置
    re_path(r'^ipk/cr$', views.IndexAdvertisingPKSetCreateView.as_view()),
    # 首页广告竞价/删除
    re_path(r'^ipk/d$', views.IndexAdvertisingPKSetDelView.as_view()),
    # 地区设置/查/改
    re_path(r'^dq/c$', views.LandSetView.as_view()),
    # 地区设置/上传
    re_path(r'^dq/cr$', views.LandSetCreateView.as_view()),
    # 地区设置/删除
    re_path(r'^dq/d$', views.LandSetDelView.as_view()),
    # 地铁设置/查/改
    re_path(r'^dt/c$', views.SubwaySetView.as_view()),
    # 地铁设置/上传
    re_path(r'^dt/cr$', views.SubwaySetCreateView.as_view()),
    # 地铁设置/删除
    re_path(r'^dt/d$', views.SubwaySetDelView.as_view()),
    # 地铁站设置/查/改
    re_path(r'^dtz/c$', views.SubwayStationSetView.as_view()),
    # 地铁站设置/上传
    re_path(r'^dtz/cr$', views.SubwayStationSetCreateView.as_view()),
    # 地铁站设置/删除
    re_path(r'^dtz/d$', views.SubwayStationSetDelView.as_view()),
    # 楼盘性质类型/查/改
    re_path(r'^lpxzlx/c$', views.BulidingChoiceClassfiySetView.as_view()),
    # 楼盘性质类型/上传
    re_path(r'^lpxzlx/cr$', views.BulidingChoiceClassfiySetCreateView.as_view()),
    # 楼盘性质类型/删除
    re_path(r'^lpxzlx/d$', views.BulidingChoiceClassfiySetDelView.as_view()),
    # 文章选择类型/查/改(内置)
    re_path(r'^wzxz/c$', views.ArticalChoiceClassfiySetView.as_view()),
    # 文章选择类型/上传
    re_path(r'^wzxz/cr$', views.ArticalChoiceClassfiySetCreateView.as_view()),
    # 文章选择类型/删除
    re_path(r'^wzxz/d$', views.ArticalChoiceClassfiySetDelView.as_view()),
    # 楼盘下拉菜单
    re_path(r'^gw/xiala$', views.BuildingXiaLaView.as_view()),
    
    # 分享堂搜索框
    re_path(r'^fxtssk/search$', views.ShareSearchView.as_view()),
    
    # # 顾问聊天记录搜索框
    # re_path(r'^search/gwltjlssk$', views.MiddlePeopleLTSearchView.as_view()),
    # 顾问访客记录搜索框
    re_path(r'^search/gwfkjlssk$', views.MiddlePeopleFWSearchView.as_view()),
    # 来电记录搜索框
    re_path(r'^search/ldjlssk$', views.ComePhoneSearchView.as_view()),
    # 专属客户搜索框
    re_path(r'^search/zskhssk$', views.CatagtleCustmersSearchView.as_view()),
    # 获客神器搜索框
    re_path(r'^search/hksqssk$', views.GiveCGODBotSearchView.as_view()),
    # 金币记录搜索框
    re_path(r'^search/jbjlssk$', views.MoneyChangeSearchView.as_view()),
    # # 入住楼盘搜索框
    # re_path(r'^search/rzlpssk$', views.HouseBuildingSearchView.as_view()),
    # # 顾问等级搜索框
    # re_path(r'^search/gwdjssk$', views.RankSearchView.as_view()),
    # 土拍搜索框
    re_path(r'^tpssk/search$', views.LandSearchView.as_view()),
    # 登陆记录搜索框
    re_path(r'^search/dljlssk$', views.LoginSearchView.as_view()),
    # 访问楼盘记录搜索框
    re_path(r'^search/fwlpjlssk$', views.QuestionBuildingSearchView.as_view()),
    # 总聊天记录搜索框/顾问
    re_path(r'^search/zltjlgwssk$', views.AllChatMiddlePeopleSearchView.as_view()),
    # 总聊天记录搜索框/用户
    re_path(r'^search/zltjlyhssk$', views.AllChatUsersSearchView.as_view()),
    # 摇号数据搜索框
    re_path(r'^search/yhsjssk$', views.LotteryNumberValueSearchView.as_view()),
    # 用户关注的文章搜索框
    re_path(r'^search/yhgzwzssk$', views.UserAttertionArticalSearchView.as_view()),
    # 用户关注的楼盘搜索框
    re_path(r'^search/yhgzlpssk$', views.UserAttertionBuildingSearchView.as_view()),
    # 用户关注的置业顾问搜索框
    re_path(r'^search/yhgzzygwssk$', views.UserAttertionMiddlePeopleSearchView.as_view()),
    # 用户摇号搜索框
    re_path(r'^search/yhyhssk$', views.UserLotterySearchView.as_view()),
    # 用户编码搜索框
    re_path(r'^search/yhbmssk$', views.UserCodeSearchView.as_view()),
    # 用户积分记录搜索框
    re_path(r'^search/yhjfjlssk$', views.UserScoresSearchView.as_view()),
    
    # ------------------------------
    
    # 系统消息搜索框
    re_path(r'^search/xtxxssk$', views.SysteamMessageSearchView.as_view()),
    # 首页广告竞价搜索框
    re_path(r'^search/syggjjssk$', views.IndexPkGaoMoneySearchView.as_view()),
    # 地区搜索框
    re_path(r'^search/dqssk$', views.LandDistarnSearchView.as_view()),
    # 地铁搜索框
    re_path(r'^search/dtssk$', views.TrainSearchView.as_view()),
    # 地铁站搜索框
    re_path(r'^search/dtzssk$', views.TrainStationSearchView.as_view()),
    # 问答搜索框
    re_path(r'^search/wdssk$', views.QuestionAnswerSearchView.as_view()),
    # 问题反馈/查/改
    re_path(r'^qaf/cg$', views.ProblemFeedbackView.as_view()),
    # 问题反馈/上传
    re_path(r'^qaf/cgc$', views.ProblemFeedbackCreateView.as_view()),
    # 问题反馈/删除
    re_path(r'^qaf/cgd$', views.ProblemFeedbackDelView.as_view()),
    # 购房百科搜索框
    re_path(r'^search/gfbkssk$', views.BuyHoseBaiKeSearchView.as_view()),
    # 一房一价搜索框
    re_path(r'^yfyj/search$', views.OneHouseOnePriceSearchView.as_view()),
    # 总楼盘销售时间搜索框
    re_path(r'^search/zlpxssjssk$', views.AllBuildingDetialSearchView.as_view()),
    # 楼盘竞价页搜索框
    re_path(r'^search/lpjjyssk$', views.BuildingDetialPkMoneySearchView.as_view()),
    
    # 顾问微聊搜索框
    re_path(r'^mp/search$', views.MiddleChatSearchView.as_view()),
    # 用户微聊搜索框
    re_path(r'^ur/search$', views.UserChatSearchView.as_view()),
    # 人工屏蔽用户
    re_path(r'^peoplework/pbyh$', views.ManualMaskingOfUsersView.as_view()),
    # 敏感词列表页/ 改
    re_path(r'^peoplework/mgclby$', views.CustomizeSensitiveWordSettingsView.as_view()),
    # 敏感词/上传
    re_path(r'^peoplework/mgclbyc$', views.CustomizeSensitiveWordSettingsCreateView.as_view()),
    # 敏感词/删除
    re_path(r'^peoplework/mgclbyd$', views.CustomizeSensitiveWordSettingsDelView.as_view()),
    # 文章搜索框/ 之 用户状态上传
    re_path(r'^peoplework/yhztcj', views.ArticaleSearchView.as_view()),
    # 敏感词查询过滤
    re_path(r'^if_bdmp$', views.SensitiveWordDepartView.as_view()),
    # 自定义屏蔽查/改
    re_path(r'^zdy/pbcg$', views.CustomMaskingView.as_view()),
    # 自定义聊天屏蔽/上传
    re_path(r'^zdy/pbsc$', views.CustomMaskingCreateView.as_view()),
    # 自定义聊天屏蔽/删除
    re_path(r'^zdy/pbsd$', views.CustomMaskingDelView.as_view()),
    # 意向登记搜索框
    re_path(r'^zdy/pbsd$', views.IntentToRegisterSearchView.as_view()),
    # 楼盘关联意向登记
    re_path(r'^gl/lpglyxdj$', views.UploadBuildingFindYXDJView.as_view()),
    # 楼盘关联一房一价
    re_path(r'^gl/lpglyfyj$', views.UploadBuildingFindYFYJView.as_view()),
    # 消息模板/查/改
    re_path(r'^xxmb/cg$', views.MessageTemplateView.as_view()),
    # 消息模板/搜索/上传
    re_path(r'^xxmb/ssc$', views.MessageTemplateCreateView.as_view()),
    # 消息模板/删除
    re_path(r'^xxmb/sd$', views.MessageTemplateDelView.as_view()),
    
    #start admin增加
    #获取所有楼盘信息和绑定楼盘
    re_path(r'^buildingDetailDone$', views.BuildingDetailDoneView.as_view())
    #end  admin增加
]
