"""
Django settings for fang_small_tuan project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


apps_path = os.path.join(BASE_DIR, 'apps')
sys.path.insert(0, apps_path)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'cmlb2frlhecpu$o20coenntg=pgx@z#0cd%=x4v2an6%fq0$3f'

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True
# DEBUG = False

# ALLOWED_HOSTS = ['127.0.0.1',
                #  'www.fangxiaotuan.site',
                #  '192.168.0.141',
                #  '192.168.0.177',
                #  'http://192.168.2.127:8000/',
                #  ]

ALLOWED_HOSTS = ['*', ]

CORS_ORIGIN_ALLOW_ALL = True  #允许所有的请求，或者设置CORS_ORIGIN_WHITELIST，二选一
CORS_ALLOW_HEADERS = ('*') #允许所有的请求头
CORS_ALLOW_CREDENTIALS = True  # 允许携带cookie

# Application definition

INSTALLED_APPS = [
    'channels',
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # cors
    'corsheaders',#放在新建应用之前
    # index
    'index.apps.IndexConfig',
    # 自定义登陆
    'authorization.apps.AuthorizationConfig',
    # 发短信应用
    'verification.apps.VerificationConfig',
    # 七牛云
    'qiniuyun.apps.QiniuyunConfig',
    # 在线聊天室系统子应用
    'chat.apps.ChatConfig',
    'ckeditor',
    'ckeditor_uploader',
    # 消息模板推送
    'template_message.apps.TemplateMessageConfig',
    # admin
    'backend_admin.apps.BackendAdminConfig',
    
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # 注意顺序，放在此处
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fang_small_tuan.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
         # 添加这一行的配置信息, 把 templates的绝对路径导入到 [] 中:
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fang_small_tuan.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': '127.0.0.1',  # 数据库主机
        'PORT': 3306,  # 数据库端口
        'USER': 'root',  # 数据库用户名
        'PASSWORD': '123456',  # 数据库用户密码
        'NAME': 'tuan'  # 数据库名字

    }
}


# redis
CACHES = {
    "default": { # 默认
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    "session": { # session
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    # 短信验证码 3号库
    "sms_code": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/3",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    # 消息库 4号库
    "message_code": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/4",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },

}
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
# SESSION_ENGINE='django.contrib.sessions.backends.db'
SESSION_CACHE_ALIAS = "session"


APPEND_SLASH=False
# APPEND_SLASH=True

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
#
# TIME_ZONE = 'UTC'

LANGUAGE_CODE = 'zh-hans' # 使用中国语言
TIME_ZONE = 'Asia/Shanghai' # 使用中国上海时间

USE_I18N = True

USE_L10N = True

# USE_TZ = True
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT  = os.path.join(BASE_DIR, 'static')

# 富文本编辑器
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
CKEDITOR_UPLOAD_PATH = 'upload/'


WX_APP_SECRET = 'cfaedc7742c39a6ff0d93c269d3491d0' # 小程序
                
# AUTH_USER_MODEL = 'authorization.Users'


#七牛云
QI_NIU_ACCESS_KEY = '8HjQeVbel_SA96w7utmPlxUlKWiQQWBIG35qrRvG'   #AK
QI_NIU_SECRET_KEY = 'J8a6pm8LXvCQAJmoWO1AVNU0ZTohoTgspaphCPyf' #SK
QI_NIU_BUCKET_NAME = 'fangxiaotuan'  #存储空间的名字


# 微信支付
WECHAT = {
        # 'APPID': 'wxcd311796ab2e3fd1',                              # 小程序ID
        'APPID': 'wx3e2f018123732318',
        # 'APPSECRET': '8bbe931d741427f9f8c95a39a123c95b',			# 小程序SECRET
        'APPSECRET': '0a1febf96b8b976aead74f009c37ef25',
        'MCH_ID': '1385314502',                                     # 商户号
        'TOTAL_FEE': '1',                                           # 总金额， 单位为“分”
        'SPBILL_CREATE_IP': '127.0.0.1',                            # 终端IP
        'NOTIFY_URL': 'http://127.0.0.1:8000/wechat/payNotify/',          # 通知地址
        'TRADE_TYPE': 'JSAPI',                                      # 交易类型
        'MERCHANT_KEY': '8bd9f5a1b550a1772b955b274d4e374f',         # 商户KEY
        # 'BODY': '商品描述',                                # 商品描述
}


ASGI_APPLICATION = 'fang_small_tuan.routing.application'


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}