# Generated by Django 2.2.5 on 2020-11-24 20:53

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttentionAretical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aretical_id', models.TextField(blank=True, null=True, verbose_name='文章id')),
                ('user_id', models.TextField(blank=True, null=True, verbose_name='用户id')),
            ],
            options={
                'verbose_name': '用户关注的文章',
                'verbose_name_plural': '用户关注的文章',
                'db_table': 'tb_attention_aretial',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AttentionMiddlePeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_people_id', models.TextField(blank=True, null=True, verbose_name='置业顾问id')),
                ('user_id', models.TextField(blank=True, null=True, verbose_name='用户id')),
            ],
            options={
                'verbose_name': '用户关注的置业顾问',
                'verbose_name_plural': '用户关注的置业顾问',
                'db_table': 'tb_attention_middle_people',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AttentionMiddlePeopleVillage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.TextField(blank=True, null=True, verbose_name='楼盘id')),
                ('user_id', models.TextField(blank=True, null=True, verbose_name='顾问id')),
            ],
            options={
                'verbose_name': '顾问关注的楼盘',
                'verbose_name_plural': '顾问关注的楼盘',
                'db_table': 'tb_attention_middle_people_village',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AttentionVillage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.TextField(blank=True, null=True, verbose_name='楼盘id')),
                ('user_id', models.TextField(blank=True, null=True, verbose_name='用户id')),
            ],
            options={
                'verbose_name': '用户关注的楼盘',
                'verbose_name_plural': '用户关注的楼盘',
                'db_table': 'tb_attention_village',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExclusiveCustmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='用户id')),
                ('user_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='普通用户姓名')),
                ('custmer_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='关注时间')),
                ('create_time', models.DateField(auto_now_add=True, null=True, verbose_name='数据创建时间')),
                ('head_img', utils.fields.QiniuField(blank=True, max_length=255, null=True, verbose_name='头像')),
            ],
            options={
                'verbose_name': '专属客户',
                'verbose_name_plural': '专属客户',
                'db_table': 'tb_exclusive_custmer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GaoBuildingDetialPKMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='准备上楼盘详情页的id')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='出价金额')),
                ('create_time', models.DateField(auto_now_add=True, null=True, verbose_name='数据创建时间')),
            ],
            options={
                'verbose_name': '楼盘详情页竞价',
                'verbose_name_plural': '楼盘详情页竞价',
                'db_table': 'tb_gao_building_detial_pk_money',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GaoIndexPKMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='准备上首页的id')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='出价金额')),
                ('create_time', models.DateField(auto_now_add=True, null=True, verbose_name='数据创建时间')),
            ],
            options={
                'verbose_name': '首页广告竞价',
                'verbose_name_plural': '首页广告竞价',
                'db_table': 'tb_gao_index_pk_money',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GoldenMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='金币修改数量')),
                ('recharge_time', models.DateField(auto_now=True, null=True, verbose_name='修改时间')),
                ('change_beacuse', models.CharField(blank=True, max_length=255, null=True, verbose_name='修改原因')),
                ('create_time', models.DateField(auto_now=True, null=True, verbose_name='数据创建时间')),
                ('choice_classfiy', models.SmallIntegerField(choices=[(0, '收入'), (1, '支出')], default=0, verbose_name='收支类型')),
            ],
            options={
                'verbose_name': '金币表',
                'verbose_name_plural': '金币表',
                'db_table': 'tb_golden_money',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IntegralSubsidiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, default=0, null=True, verbose_name='积分修改数量数')),
                ('score_create_time', models.DateField(auto_now=True, null=True, verbose_name='修改时间')),
                ('change_beacuse', models.CharField(blank=True, max_length=255, null=True, verbose_name='修改原因')),
                ('create_time', models.DateField(auto_now=True, null=True, verbose_name='数据创建时间')),
                ('choice_classfiy', models.SmallIntegerField(choices=[(0, '增加'), (1, '减少')], default=0, verbose_name='积分加减类型')),
            ],
            options={
                'verbose_name': '积分表',
                'verbose_name_plural': '积分表',
                'db_table': 'tb_integral_subsidiary',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MiddlePeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=255, verbose_name='昵称')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('header_img', utils.fields.QiniuField(blank=True, max_length=255, null=True, verbose_name='头像')),
                ('personal_introduce', models.CharField(blank=True, max_length=255, null=True, verbose_name='个人介绍')),
                ('really_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='真实姓名')),
                ('ID_card', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='身份证')),
                ('wechat_number', models.TextField(blank=True, null=True, verbose_name='微信号')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('rank', models.CharField(blank=True, max_length=10, null=True, verbose_name='级别')),
                ('bussiness_building', models.CharField(blank=True, max_length=255, null=True, verbose_name='主营楼盘')),
                ('browse_count', models.IntegerField(default=0, verbose_name='浏览量')),
                ('live_limit', models.IntegerField(default=0, verbose_name='活跃度')),
                ('click_count', models.IntegerField(default=0, verbose_name=' 点赞数')),
                ('call_mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='通过的电话')),
                ('wechat_talk', models.TextField(blank=True, null=True, verbose_name='微聊')),
                ('exclusive_people', models.CharField(blank=True, max_length=50, null=True, verbose_name='专属客户')),
                ('integral', models.IntegerField(blank=True, default=0, null=True, verbose_name='积分')),
                ('golden_money', models.IntegerField(blank=True, default=0, null=True, verbose_name='金币')),
                ('give_price_history', models.CharField(blank=True, max_length=100, null=True, verbose_name='出价记录')),
                ('invitation_code', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='邀请码')),
                ('two_wei_ma', utils.fields.QiniuField(blank=True, max_length=5000, null=True, verbose_name='二维码')),
                ('work_pai', utils.fields.QiniuField(blank=True, max_length=5000, null=True, verbose_name='工牌')),
            ],
            options={
                'verbose_name': '置业顾问',
                'verbose_name_plural': '置业顾问',
                'db_table': 'tb_middle_people',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MiddlePeopleHistoryMessageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='用户id')),
                ('middle_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='顾问id')),
                ('content', models.TextField(blank=True, null=True, verbose_name='说话记录')),
                ('create_time', models.DateField(auto_now=True, null=True, verbose_name='数据创建时间')),
            ],
            options={
                'verbose_name': '顾问聊天记录',
                'verbose_name_plural': '顾问聊天记录',
                'db_table': 'tb_middle_people_history_message_record',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MiddleUnionId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_open_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='小程序openid')),
                ('gong_open_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='公众号openid')),
                ('union_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='联合id')),
            ],
            options={
                'verbose_name': 'unionid中间表',
                'verbose_name_plural': 'unionid中间表',
                'db_table': 'tb_middle_union_id',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MyPhoneCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='来电人名称')),
                ('user_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='通过电话的id')),
                ('phone_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='通话创建时间')),
                ('user_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='电话号码')),
                ('create_time', models.DateField(auto_now_add=True, null=True, verbose_name='数据创建时间')),
                ('head_img', utils.fields.QiniuField(blank=True, max_length=255, null=True, verbose_name='头像')),
                ('choice_classfiy', models.SmallIntegerField(choices=[(0, '已结'), (1, '未接')], default=0, verbose_name='接打类型')),
            ],
            options={
                'verbose_name': '我的来电',
                'verbose_name_plural': '我的来电',
                'db_table': 'tb_my_phone_call',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MyWeChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='用户id')),
                ('user_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='普通用户姓名')),
                ('custmer_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='沟通时间')),
                ('create_time', models.DateField(auto_now_add=True, null=True, verbose_name='数据创建时间')),
                ('head_img', utils.fields.QiniuField(blank=True, max_length=255, null=True, verbose_name='头像')),
                ('where_come_from', models.TextField(blank=True, null=True, verbose_name='来源')),
                ('choice_classfiy', models.SmallIntegerField(choices=[(0, '已读'), (1, '未读')], default=0, verbose_name='读取类型')),
            ],
            options={
                'verbose_name': '我的微聊',
                'verbose_name_plural': '我的微聊',
                'db_table': 'tb_my_we_chat',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QuestionFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_classfiy', models.SmallIntegerField(choices=[(0, '程序错误'), (1, '优化建议'), (2, '数据错误/缺失'), (3, '其他')], default=0, verbose_name='反馈类型')),
                ('my_create_time', models.DateField(auto_now_add=True, null=True, verbose_name='问题创建时间')),
                ('my_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='问题描述内容')),
                ('question_img', utils.fields.QiniuField(blank=True, max_length=5000, null=True, verbose_name='问题图片')),
                ('feedback_phone', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='联系方式')),
                ('img1', utils.fields.QiniuField(blank=True, max_length=5000, null=True, verbose_name='问题图片')),
            ],
            options={
                'verbose_name': '问题反馈',
                'verbose_name_plural': '问题反馈',
                'db_table': 'tb_question_feedback',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReallyNameMiddlePeopleShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='用户id')),
                ('middle_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='顾问id')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='来源')),
                ('create_time', models.DateField(auto_now_add=True, null=True, verbose_name='数据创建时间')),
            ],
            options={
                'verbose_name': '获客神器',
                'verbose_name_plural': '获客神器',
                'db_table': 'tb_really_name_middle_people_share',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserCodeNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('really_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名')),
                ('create_time', models.DateField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='用户编码')),
            ],
            options={
                'verbose_name': '用户编码',
                'verbose_name_plural': '用户编码',
                'db_table': 'tb_user_code_number',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserHistoryMessageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='用户id')),
                ('middle_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='顾问id')),
                ('content', models.TextField(blank=True, null=True, verbose_name='说话记录')),
                ('create_time', models.DateField(auto_now_add=True, null=True, verbose_name='数据创建时间')),
            ],
            options={
                'verbose_name': '用户聊天记录',
                'verbose_name_plural': '用户聊天记录',
                'db_table': 'tb_user_history_message_record',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserLotteryNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='用户编码')),
                ('really_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名')),
            ],
            options={
                'verbose_name': '用户摇号',
                'verbose_name_plural': '用户摇号',
                'db_table': 'tb_user_lottery_number',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WhoZanMiddelPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='用户id')),
                ('middle_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='顾问id')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='数据创建时间')),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.MiddlePeople', verbose_name='置业顾问名称')),
            ],
            options={
                'verbose_name': '顾问点赞记录',
                'verbose_name_plural': '顾问点赞记录',
                'db_table': 'tb_who_zan_middle_people',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WhoLookMiddelPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='用户id')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='数据创建时间')),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.MiddlePeople', verbose_name='置业顾问名称')),
            ],
            options={
                'verbose_name': '顾问访客',
                'verbose_name_plural': '顾问访客',
                'db_table': 'tb_who_look_middle_people',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='open_id')),
                ('user_uuid', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='user_uuid')),
                ('nick_name', models.CharField(max_length=255, verbose_name='昵称')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('header_img', utils.fields.QiniuField(max_length=255, verbose_name='头像')),
                ('personal_introduce', models.CharField(blank=True, max_length=255, null=True, verbose_name='个人介绍')),
                ('adreess', models.CharField(blank=True, max_length=255, null=True, verbose_name='地址')),
                ('really_name', models.CharField(max_length=25, verbose_name='真实姓名')),
                ('ID_card', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='身份证')),
                ('wechat_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='微信号')),
                ('middle_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='顾问id')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('if_middle_people', models.SmallIntegerField(choices=[(0, '普通用户'), (1, '置业顾问')], default=0, verbose_name='是否是置业顾问')),
                ('fk_aretical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.AttentionAretical', verbose_name='关注的文章')),
                ('fk_building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.AttentionVillage', verbose_name='关注的楼盘')),
                ('fk_mp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.AttentionMiddlePeople', verbose_name='关注的置业顾问')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'tb_user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, null=True, verbose_name='数据创建时间')),
                ('classfiy1', models.CharField(blank=True, max_length=50, null=True, verbose_name='举报类型1')),
                ('classfiy2', models.CharField(blank=True, max_length=50, null=True, verbose_name='举报类型2')),
                ('upload_img1', utils.fields.QiniuField(blank=True, max_length=500, null=True, verbose_name='上传问题图片1')),
                ('upload_img2', utils.fields.QiniuField(blank=True, max_length=500, null=True, verbose_name='上传问题图片2')),
                ('upload_img3', utils.fields.QiniuField(blank=True, max_length=500, null=True, verbose_name='上传问题图片3')),
                ('upload_img4', utils.fields.QiniuField(blank=True, max_length=500, null=True, verbose_name='上传问题图片4')),
                ('upload_img5', utils.fields.QiniuField(blank=True, max_length=500, null=True, verbose_name='上传问题图片5')),
                ('upload_img6', utils.fields.QiniuField(blank=True, max_length=500, null=True, verbose_name='上传问题图片6')),
                ('content', models.CharField(blank=True, max_length=9999, null=True, verbose_name='问题描述')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('user_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户名')),
                ('bad_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='被举报人id')),
                ('fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.Users', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '举报表',
                'verbose_name_plural': '举报表',
                'db_table': 'tb_user_report',
                'managed': True,
            },
        ),
    ]
