# Generated by Django 2.2.5 on 2020-11-24 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0001_initial'),
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlotterynumber',
            name='build_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.BuildingDetial', verbose_name='楼盘'),
        ),
        migrations.AddField(
            model_name='userlotterynumber',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.Users', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='userhistorymessagerecord',
            name='fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.Users', verbose_name='用户名称'),
        ),
        migrations.AddField(
            model_name='usercodenumber',
            name='build_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.BuildingDetial', verbose_name='楼盘'),
        ),
        migrations.AddField(
            model_name='usercodenumber',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.Users', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='reallynamemiddlepeopleshare',
            name='fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.MiddlePeople', verbose_name='所属顾问'),
        ),
        migrations.AddField(
            model_name='questionfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.Users', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='mywechat',
            name='middle_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.MiddlePeople', verbose_name='置业顾问'),
        ),
        migrations.AddField(
            model_name='myphonecall',
            name='middle_people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.MiddlePeople', verbose_name='所属置业顾问'),
        ),
        migrations.AddField(
            model_name='middleunionid',
            name='fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.Users', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='middlepeoplehistorymessagerecord',
            name='fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.MiddlePeople', verbose_name='置业顾问名称'),
        ),
        migrations.AddField(
            model_name='middlepeople',
            name='building_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.BuildingDetial', verbose_name='楼盘'),
        ),
        migrations.AddField(
            model_name='middlepeople',
            name='user_fk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authorization.Users', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='integralsubsidiary',
            name='fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.MiddlePeople', verbose_name='置业顾问'),
        ),
        migrations.AddField(
            model_name='goldenmoney',
            name='fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.MiddlePeople', verbose_name='置业顾问'),
        ),
        migrations.AddField(
            model_name='gaoindexpkmoney',
            name='fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.MiddlePeople', verbose_name='置业顾问名称'),
        ),
        migrations.AddField(
            model_name='gaobuildingdetialpkmoney',
            name='fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.MiddlePeople', verbose_name='置业顾问名称'),
        ),
        migrations.AddField(
            model_name='exclusivecustmer',
            name='middle_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.MiddlePeople', verbose_name='置业顾问'),
        ),
    ]
