# Generated by Django 2.2.5 on 2020-11-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_auto_20201128_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='middlepeople',
            name='room_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='聊天房间号'),
        ),
    ]
