# Generated by Django 2.2.5 on 2020-12-01 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_middlepeople_room_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSealStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now=True, verbose_name='数据创建时间')),
                ('statue', models.BooleanField(blank=True, default=False, null=True, verbose_name='是否封号')),
                ('choice_classfiy', models.SmallIntegerField(choices=[(0, '无'), (1, '7天'), (2, '30天'), (3, '永久')], default=0, verbose_name='封印类型')),
                ('fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.Users', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '用户封禁状态',
                'verbose_name_plural': '用户封禁状态',
                'db_table': 'tb_user_seal_status',
                'managed': True,
            },
        ),
    ]
