# Generated by Django 2.2.5 on 2020-12-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_usersealstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensitiveWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now=True, verbose_name='数据创建时间')),
                ('word', models.CharField(blank=True, max_length=255, null=True, verbose_name='词')),
                ('choice_classfiy', models.SmallIntegerField(choices=[(0, '无'), (1, '顾问'), (2, '用户'), (3, '全局')], default=0, verbose_name='作用域')),
            ],
            options={
                'verbose_name': '敏感词',
                'verbose_name_plural': '敏感词',
                'db_table': 'tb_sensitive_word',
                'managed': True,
            },
        ),
    ]
