# Generated by Django 2.2.5 on 2020-12-01 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_sensitiveword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersealstatus',
            name='fk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.Users', verbose_name='用户id'),
        ),
    ]
