# Generated by Django 2.2.5 on 2020-12-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0011_auto_20201202_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attentionaretical',
            name='aretical_id',
            field=models.TextField(blank=True, null=True, verbose_name='文章id'),
        ),
        migrations.AlterField(
            model_name='attentionmiddlepeople',
            name='middle_people_id',
            field=models.TextField(blank=True, null=True, verbose_name='置业顾问id'),
        ),
        migrations.AlterField(
            model_name='attentionmiddlepeoplevillage',
            name='building_id',
            field=models.TextField(blank=True, null=True, verbose_name='楼盘id'),
        ),
        migrations.AlterField(
            model_name='attentionvillage',
            name='building_id',
            field=models.TextField(blank=True, null=True, verbose_name='楼盘id'),
        ),
    ]
