# Generated by Django 2.2.5 on 2020-12-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0012_auto_20201202_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensitiveword',
            name='if_talk',
            field=models.BooleanField(default=False, verbose_name='是否禁言'),
        ),
    ]
