# Generated by Django 2.2.5 on 2020-12-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0014_maxconnectionandmaxpeopleandmaxcountview'),
    ]

    operations = [
        migrations.AddField(
            model_name='maxconnectionandmaxpeopleandmaxcountview',
            name='ip_count',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='最大请求次数'),
        ),
    ]
