# Generated by Django 2.2.5 on 2020-12-06 17:28

from django.db import migrations, models
import django.db.models.deletion
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0016_auto_20201202_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageChatListView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='数据创建时间')),
                ('header_image', utils.fields.QiniuField(blank=True, max_length=255, null=True, verbose_name='用户头像')),
                ('message', models.CharField(blank=True, max_length=500, null=True, verbose_name='消息记录')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户名称')),
                ('pid', models.CharField(blank=True, max_length=255, null=True, verbose_name='列表中显示的顾问id')),
                ('fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.Users', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '即时通讯聊天列表',
                'verbose_name_plural': '即时通讯聊天列表',
                'db_table': 'tb_message_chat_list',
                'managed': True,
            },
        ),
    ]
