# Generated by Django 2.2.5 on 2020-12-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0017_messagechatlistview'),
    ]

    operations = [
        migrations.AddField(
            model_name='middlepeoplehistorymessagerecord',
            name='room',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='当时的房间号'),
        ),
        migrations.AddField(
            model_name='userhistorymessagerecord',
            name='room',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='当时的房间号'),
        ),
        migrations.AddField(
            model_name='users',
            name='chat_room',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='房间号'),
        ),
    ]
