# Generated by Django 2.2.5 on 2020-12-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0018_auto_20201207_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagechatlistview',
            name='mp_room',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='顾问的房间号'),
        ),
        migrations.AddField(
            model_name='messagechatlistview',
            name='ur_room',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='用户的房间号'),
        ),
    ]
