# Generated by Django 2.2.5 on 2020-12-09 00:23

from django.db import migrations, models
import django.db.models.deletion
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0019_auto_20201208_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='数据创建时间')),
                ('token', models.CharField(blank=True, max_length=255, null=True, verbose_name='token')),
            ],
            options={
                'verbose_name': 'token',
                'verbose_name_plural': 'token',
                'db_table': 'tb_token',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='userhistorymessagerecord',
            name='middle_id',
        ),
        migrations.RemoveField(
            model_name='userhistorymessagerecord',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userhistorymessagerecord',
            name='header_image',
            field=utils.fields.QiniuField(blank=True, max_length=255, null=True, verbose_name='用户头像'),
        ),
        migrations.AddField(
            model_name='userhistorymessagerecord',
            name='user_bei_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='被聊人id'),
        ),
        migrations.AlterField(
            model_name='middlepeoplehistorymessagerecord',
            name='create_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='数据创建时间'),
        ),
        migrations.AlterField(
            model_name='userhistorymessagerecord',
            name='create_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='数据创建时间'),
        ),
        migrations.AlterField(
            model_name='userhistorymessagerecord',
            name='fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.Users', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='userhistorymessagerecord',
            name='room',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='房间号'),
        ),
    ]
