# Generated by Django 2.2.5 on 2020-12-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0021_auto_20201215_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlotterynumber',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='用户编码'),
        ),
    ]
