# Generated by Django 2.2.5 on 2020-12-16 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0022_auto_20201216_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whozanmiddelpeople',
            name='fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authorization.MiddlePeople', verbose_name='置业顾问名称'),
        ),
    ]
