# Generated by Django 2.2.5 on 2020-12-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0023_auto_20201216_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginbuildingrecord',
            name='building_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='楼盘id'),
        ),
        migrations.AlterField(
            model_name='userloginbuildingrecord',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='数据创建时间'),
        ),
    ]
