# Generated by Django 2.2.5 on 2020-12-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0024_auto_20201216_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginrecord',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='数据创建时间'),
        ),
    ]
