# Generated by Django 2.2.5 on 2020-12-18 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0025_auto_20201217_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEveryDayPermetionStatue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_choice', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='今日是否签到')),
                ('q_count', models.CharField(blank=True, max_length=255, null=True, verbose_name='连续签到天数')),
                ('g_choice', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否授权关注公众号')),
                ('fn_choice', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否分享给新用户')),
                ('fn_count', models.CharField(blank=True, max_length=255, null=True, verbose_name='分享给新用户次数')),
                ('fo_choice', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否分享给老用户')),
                ('fo_count', models.CharField(blank=True, max_length=255, null=True, verbose_name='分享给老用户次数')),
                ('zf_choice', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否转发朋友圈')),
                ('zf_count', models.CharField(blank=True, max_length=255, null=True, verbose_name='转发朋友圈次数')),
                ('fxt_choice', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否发布分享唐')),
                ('fxt_count', models.CharField(blank=True, max_length=255, null=True, verbose_name='发布分享唐次数')),
                ('tgxx_choice', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否提供重要信息')),
                ('tgxx_count', models.CharField(blank=True, max_length=255, null=True, verbose_name='提供重要信息次数')),
                ('yqrz_choice', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否邀请置业顾问入驻')),
                ('yqrz_count', models.CharField(blank=True, max_length=255, null=True, verbose_name='邀请置业顾问入驻次数')),
                ('sclp_choice', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否上传楼盘信息')),
                ('sclp_count', models.CharField(blank=True, max_length=255, null=True, verbose_name='上传楼盘信息次数')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='数据创建时间')),
                ('fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.MiddlePeople', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '用户每日任务状态栏',
                'verbose_name_plural': '用户每日任务状态栏',
                'db_table': 'tb_user_everyday_permetion_statue',
                'managed': True,
            },
        ),
    ]
