# Generated by Django 2.2.5 on 2020-12-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0026_usereverydaypermetionstatue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersealstatus',
            name='fk',
        ),
        migrations.AddField(
            model_name='usersealstatus',
            name='open_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='用户open_id'),
        ),
        migrations.AlterField(
            model_name='usersealstatus',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='数据创建时间'),
        ),
    ]
