# Generated by Django 2.2.5 on 2020-12-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0027_auto_20201219_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaoindexpkmoney',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='数据创建时间'),
        ),
    ]
