# Generated by Django 2.2.5 on 2020-12-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0028_auto_20201219_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaobuildingdetialpkmoney',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='数据创建时间'),
        ),
    ]
