# Generated by Django 2.2.5 on 2020-11-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_winpkhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingdetial',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='数据创建时间'),
        ),
    ]
