# Generated by Django 2.2.5 on 2020-11-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_buildingdetial_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingdetial',
            name='create_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='数据创建时间'),
        ),
    ]
