# Generated by Django 2.2.5 on 2020-11-27 22:28

from django.db import migrations, models
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20201127_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingdetial',
            name='union_building_test_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='楼盘联合id'),
        ),
        migrations.AddField(
            model_name='buildingstatuetimesale',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='buildingdetial',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='数据创建时间'),
        ),
        migrations.AlterField(
            model_name='buildingdetial',
            name='house_count',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='房源套数'),
        ),
        migrations.AlterField(
            model_name='buildingdetial',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='buildingdetial',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='buildingdetial',
            name='open_house_count',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='开盘房源套数'),
        ),
        migrations.AlterField(
            model_name='buildingdetial',
            name='open_price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='开盘价格'),
        ),
        migrations.AlterField(
            model_name='buildingdetial',
            name='people_count',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='报名人数'),
        ),
        migrations.AlterField(
            model_name='buildingdetial',
            name='premises_location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='楼盘地址'),
        ),
        migrations.AlterField(
            model_name='buildingdetial',
            name='sale_building_location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='售楼地址'),
        ),
        migrations.AlterField(
            model_name='buildingdetial',
            name='win_probability',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='摇中概率'),
        ),
        migrations.AlterField(
            model_name='buildingimage',
            name='create_time',
            field=models.DateField(auto_now=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='houseimage',
            name='choice_classfiy',
            field=models.SmallIntegerField(choices=[(0, '其他'), (1, '两室一厅'), (2, '三室一厅'), (3, '四室一厅'), (4, '五室及以上'), (4, '一室一厅')], default=0, verbose_name='户型样式'),
        ),
        migrations.AlterField(
            model_name='landauction',
            name='acquisition_company',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='竞得方'),
        ),
        migrations.AlterField(
            model_name='landauction',
            name='deal_all_price',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='成交总价'),
        ),
        migrations.AlterField(
            model_name='landauction',
            name='deal_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='成交日期'),
        ),
        migrations.AlterField(
            model_name='landauction',
            name='end_parice',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='成交价'),
        ),
        migrations.AlterField(
            model_name='landauction',
            name='give_area',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='出让面积'),
        ),
        migrations.AlterField(
            model_name='landauction',
            name='give_year',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='出让年限'),
        ),
        migrations.AlterField(
            model_name='landauction',
            name='land_ask_for',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='宗地要求'),
        ),
        migrations.AlterField(
            model_name='landauction',
            name='land_img',
            field=utils.fields.QiniuField(blank=True, max_length=500, null=True, verbose_name='地块图片'),
        ),
        migrations.AlterField(
            model_name='landauction',
            name='land_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='地块名称'),
        ),
        migrations.AlterField(
            model_name='landauction',
            name='land_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='宗地编号'),
        ),
        migrations.AlterField(
            model_name='landauction',
            name='land_position',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='宗地位置'),
        ),
        migrations.AlterField(
            model_name='landauction',
            name='land_region',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='地块区域'),
        ),
        migrations.AlterField(
            model_name='landauction',
            name='land_use',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='土地用途'),
        ),
        migrations.AlterField(
            model_name='landauction',
            name='late',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='landauction',
            name='long',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='landauction',
            name='map',
            field=utils.fields.QiniuField(blank=True, max_length=500, null=True, verbose_name='地图'),
        ),
        migrations.AlterField(
            model_name='landauction',
            name='max_volume_rate',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='最大容积率'),
        ),
        migrations.AlterField(
            model_name='landauction',
            name='nuddle_price',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='楼面价'),
        ),
        migrations.AlterField(
            model_name='landauction',
            name='overflow',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='溢价率'),
        ),
        migrations.AlterField(
            model_name='landauction',
            name='start_parice',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='起拍价'),
        ),
        migrations.AlterField(
            model_name='toldpurpose',
            name='lottery_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='摇号编码'),
        ),
    ]
