# Generated by Django 2.2.5 on 2020-11-30 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20201130_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='onehouseoneprice',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subs', to='index.OneHouseOnePrice', verbose_name='上级楼层'),
        ),
    ]
