# Generated by Django 2.2.5 on 2020-12-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_onehouseoneprice_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='onehouseoneprice',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
    ]
