# Generated by Django 2.2.5 on 2020-12-01 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_onehouseoneprice_create_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toldpurpose',
            name='lottery_number',
        ),
        migrations.RemoveField(
            model_name='toldpurpose',
            name='village_name',
        ),
        migrations.AddField(
            model_name='toldpurpose',
            name='building_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='楼盘名称'),
        ),
        migrations.AddField(
            model_name='toldpurpose',
            name='buy_house_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='购房登记号'),
        ),
        migrations.AddField(
            model_name='toldpurpose',
            name='find_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='查档编号'),
        ),
        migrations.AddField(
            model_name='toldpurpose',
            name='fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.BuildingDetial', verbose_name='楼盘'),
        ),
        migrations.AddField(
            model_name='toldpurpose',
            name='house_classfiy',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='家庭类型'),
        ),
        migrations.AddField(
            model_name='toldpurpose',
            name='other_ID_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='其他人身份证号'),
        ),
        migrations.AddField(
            model_name='toldpurpose',
            name='other_lottery_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='家庭成员姓名'),
        ),
        migrations.AlterField(
            model_name='toldpurpose',
            name='ID_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='购房人身份证号'),
        ),
        migrations.AlterField(
            model_name='toldpurpose',
            name='create_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='toldpurpose',
            name='lottery_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='购房人姓名'),
        ),
        migrations.CreateModel(
            name='LotteryResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='序号')),
                ('buy_house_number', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='购房登记号')),
                ('create_time', models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间')),
                ('fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.BuildingDetial', verbose_name='楼盘')),
            ],
            options={
                'verbose_name': '购房登记号顺序表(摇号结果)',
                'verbose_name_plural': '购房登记号顺序表(摇号结果)',
                'db_table': 'tb_lottery_result',
                'managed': True,
            },
        ),
    ]
