# Generated by Django 2.2.5 on 2020-12-01 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20201201_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onehouseoneprice',
            name='building_detial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.BuildingDetial', verbose_name='楼盘详情'),
        ),
    ]
