# Generated by Django 2.2.5 on 2020-12-02 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20201201_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onehouseoneprice',
            old_name='result1',
            new_name='result',
        ),
        migrations.RemoveField(
            model_name='onehouseoneprice',
            name='result2',
        ),
    ]
