# Generated by Django 2.2.5 on 2020-12-02 11:37

from django.db import migrations, models
import django.db.models.deletion
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_remove_onehouseoneprice_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingOneHouseOnePriceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_image', utils.fields.QiniuField(blank=True, max_length=5000, null=True, verbose_name='图片')),
                ('create_time', models.DateField(auto_now=True, null=True, verbose_name='创建时间')),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.BuildingDetial', verbose_name='楼盘详情')),
            ],
            options={
                'verbose_name': '生成的一房一价图片',
                'verbose_name_plural': '生成的一房一价图片',
                'db_table': 'tb_building_one_house_one_price_image',
                'managed': True,
            },
        ),
    ]
