# Generated by Django 2.2.5 on 2020-12-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_buildingonehouseonepriceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseimage',
            name='choice_classfiy',
            field=models.SmallIntegerField(choices=[(0, '一室一厅'), (1, '一室两厅'), (2, '两室一厅'), (3, '两室两厅'), (4, '三室一厅'), (5, '三室两厅'), (6, '四室一厅'), (7, '四室两厅'), (8, '五室一厅'), (9, '五室两厅')], default=0, verbose_name='户型样式'),
        ),
    ]
