# Generated by Django 2.2.5 on 2020-12-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_auto_20201206_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotteryresult',
            name='buy_house_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='购房登记号'),
        ),
        migrations.AlterField(
            model_name='toldpurpose',
            name='buy_house_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='购房登记号'),
        ),
    ]
