# Generated by Django 2.2.5 on 2020-12-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_auto_20201206_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onehouseoneprice',
            name='area',
        ),
        migrations.RemoveField(
            model_name='onehouseoneprice',
            name='classfiy',
        ),
        migrations.RemoveField(
            model_name='onehouseoneprice',
            name='decorate_type',
        ),
        migrations.RemoveField(
            model_name='onehouseoneprice',
            name='decorate_type_price',
        ),
        migrations.RemoveField(
            model_name='onehouseoneprice',
            name='house_ceng',
        ),
        migrations.RemoveField(
            model_name='onehouseoneprice',
            name='house_xing',
        ),
        migrations.RemoveField(
            model_name='onehouseoneprice',
            name='if_sale',
        ),
        migrations.RemoveField(
            model_name='onehouseoneprice',
            name='lottery_ci',
        ),
        migrations.RemoveField(
            model_name='onehouseoneprice',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='onehouseoneprice',
            name='water_money',
        ),
        migrations.AddField(
            model_name='onehouseoneprice',
            name='build_company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='开发商'),
        ),
        migrations.AddField(
            model_name='onehouseoneprice',
            name='create_area',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='建面面积'),
        ),
        migrations.AddField(
            model_name='onehouseoneprice',
            name='give_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='核发日期'),
        ),
        migrations.AddField(
            model_name='onehouseoneprice',
            name='in_area',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='套内面积'),
        ),
        migrations.AddField(
            model_name='onehouseoneprice',
            name='lottery_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='地块编号'),
        ),
        migrations.AddField(
            model_name='onehouseoneprice',
            name='public_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='公示日期'),
        ),
        migrations.AddField(
            model_name='onehouseoneprice',
            name='will_sale_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='预售证号'),
        ),
        migrations.AlterField(
            model_name='onehouseoneprice',
            name='create_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='数据创建时间'),
        ),
    ]
