# Generated by Django 2.2.5 on 2020-12-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_auto_20201206_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toldpurpose',
            name='audit_status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'no'), (1, 'yes')], default=0, null=True, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='toldpurpose',
            name='if_win_lottery',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'no'), (1, 'yes')], default=0, null=True, verbose_name='是否中签'),
        ),
    ]
