# Generated by Django 2.2.5 on 2020-12-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_auto_20201207_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingdetial',
            name='unit_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='参考单价'),
        ),
    ]
