# Generated by Django 2.2.5 on 2020-12-16 15:25

from django.db import migrations, models
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0024_auto_20201215_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='阅读量'),
        ),
        migrations.AddField(
            model_name='article',
            name='zanc',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='点赞量'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author_img',
            field=utils.fields.QiniuField(blank=True, max_length=500, null=True, verbose_name='作者头像'),
        ),
        migrations.AlterField(
            model_name='article',
            name='new_img',
            field=utils.fields.QiniuField(blank=True, max_length=500, null=True, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='zancount',
            name='choice_classfiy',
            field=models.SmallIntegerField(choices=[(0, '楼盘评论赞'), (1, '文章赞'), (2, '赞回答里面的答')], default=0, verbose_name='点赞分类'),
        ),
        migrations.AlterField(
            model_name='zancount',
            name='type_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='需要点赞内容的id'),
        ),
    ]
