# Generated by Django 2.2.5 on 2020-12-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0025_auto_20201216_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zancount',
            name='create_time',
            field=models.DateField(auto_now=True, null=True, verbose_name='创建时间'),
        ),
    ]
