# Generated by Django 2.2.5 on 2020-12-16 16:25

from django.db import migrations, models
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0026_auto_20201216_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyhousehundreddepartment',
            name='click_zan',
            field=models.IntegerField(default=0, verbose_name='点赞量'),
        ),
        migrations.AlterField(
            model_name='buyhousehundreddepartment',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='问题创建时间'),
        ),
        migrations.AlterField(
            model_name='buyhousehundreddepartment',
            name='text_img',
            field=utils.fields.QiniuField(blank=True, max_length=500, null=True, verbose_name='资料图片'),
        ),
        migrations.AlterField(
            model_name='buyhousehundreddepartment',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='buyhousehundreddepartment',
            name='two_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='二级标题'),
        ),
        migrations.AlterField(
            model_name='zancount',
            name='choice_classfiy',
            field=models.SmallIntegerField(choices=[(0, '楼盘评论赞'), (1, '文章赞'), (2, '赞回答里面的答'), (3, '顾问里面的加赞'), (4, '购房百科的赞')], default=0, verbose_name='点赞分类'),
        ),
        migrations.AlterField(
            model_name='zancount',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
