# Generated by Django 2.2.5 on 2020-12-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0028_auto_20201216_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicplan',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
