# Generated by Django 2.2.5 on 2020-12-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0029_auto_20201217_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='onehouseoneprice',
            name='all_house_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='总套数'),
        ),
        migrations.AddField(
            model_name='onehouseoneprice',
            name='house_use',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='使用类型'),
        ),
        migrations.AlterField(
            model_name='onehouseoneprice',
            name='all_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='总价'),
        ),
        migrations.AlterField(
            model_name='onehouseoneprice',
            name='gave_house',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='得房率'),
        ),
        migrations.AlterField(
            model_name='onehouseoneprice',
            name='one_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='单价'),
        ),
    ]
