# Generated by Django 2.2.5 on 2020-12-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0030_auto_20201217_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onehouseoneprice',
            name='all_price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='总价'),
        ),
        migrations.AlterField(
            model_name='onehouseoneprice',
            name='one_price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='单价'),
        ),
    ]
