# Generated by Django 2.2.5 on 2020-12-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0031_auto_20201217_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onehouseoneprice',
            name='all_house_count',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='总套数'),
        ),
        migrations.AlterField(
            model_name='onehouseoneprice',
            name='gave_house',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='得房率'),
        ),
    ]
