# Generated by Django 2.2.5 on 2020-12-17 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0032_auto_20201217_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onehouseoneprice',
            old_name='all_house_count',
            new_name='all_tao_count',
        ),
    ]
