# Generated by Django 2.2.5 on 2020-12-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0034_auto_20201217_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onehouseoneprice',
            name='all_house_count',
        ),
        migrations.AddField(
            model_name='onehouseoneprice',
            name='all_tao_count',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='总套数'),
        ),
    ]
