# Generated by Django 2.2.5 on 2020-12-21 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0035_auto_20201217_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingstatuetimesale',
            name='history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.HistoryLottery', verbose_name='历史摇号id'),
        ),
    ]
